spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  kafka:
    producer:
      bootstrap-servers: localhost:9092

server:
  port: 30100

app:
  flt:
    populator:
      enabled: true
    kafka.enabled: true